#!/usr/bin/env python3
"""Inline brand/fonts/ into a preview so the HTML is a single sendable file.

    python3 design/previews/inline-fonts.py design/previews/*.html

`CLAUDE.md` requires every preview to stand alone. Both previews linked
`../../brand/fonts/fonts.css`, which meant they rendered correctly from this
repository and silently fell back to a system face from an inbox or a USB
stick — and a missing typeface fails without an error, so nobody would be told.

This replaces that link with the same @font-face block carrying the seven woff2
as data URIs. It is idempotent: run it again and it reports nothing to do.
All seven faces go in whether or not a given file uses all of them, because a
weight that appears later must not fall back silently — the same reasoning
`brand/fonts/fonts.css` records for the CJK subsets it does not ship.
"""
import base64, os, re, sys

HERE  = os.path.dirname(os.path.abspath(__file__))
ROOT  = os.path.dirname(os.path.dirname(HERE))
FONTS = os.path.join(ROOT, "TIS-Terrain", "brand", "fonts")
if not os.path.isdir(FONTS):
    FONTS = os.path.normpath(os.path.join(HERE, "..", "..", "brand", "fonts"))

FACES = [("Urbanist", w) for w in (400, 500, 600, 700)] + \
        [("Inconsolata", w) for w in (400, 500, 600)]

LINK = re.compile(r'[ \t]*<link[^>]+href="[^"]*brand/fonts/fonts\.css"[^>]*>\n?')

def block():
    out = ["<style>",
           "/* TIS Terrain typefaces, inlined so this file stands alone.",
           "   Generated by design/previews/inline-fonts.py from brand/fonts/ —",
           "   do not hand-edit. Urbanist 400/500/600/700, Inconsolata 400/500/600.",
           "   English-only by decision: there is no CJK face here on purpose. */"]
    for fam, w in FACES:
        path = os.path.join(FONTS, "%s-%d.woff2" % (fam, w))
        b64 = base64.b64encode(open(path, "rb").read()).decode()
        out.append("@font-face{font-family:'%s';font-style:normal;font-weight:%d;"
                   "font-display:swap;src:url(data:font/woff2;base64,%s) format('woff2')}"
                   % (fam, w, b64))
    out.append("</style>")
    return "\n".join(out) + "\n"

def main(paths):
    css = block()
    for p in paths:
        s = open(p, encoding="utf-8").read()
        if "data:font/woff2" in s:
            print("%-46s already inlined" % os.path.basename(p)); continue
        s2, n = LINK.subn(lambda m: css, s, count=1)
        if not n:
            print("%-46s no fonts.css link found" % os.path.basename(p)); continue
        open(p, "w", encoding="utf-8").write(s2)
        print("%-46s inlined 7 faces, %+d KB" % (os.path.basename(p), (len(s2)-len(s))//1024))

if __name__ == "__main__":
    main(sys.argv[1:] or [os.path.join(HERE, f) for f in sorted(os.listdir(HERE))
                          if f.endswith(".html")])
